### ISSUE TITLE
Getting started - possible to simplify?

### ISSUE THREAD

**Issue by use** [gruntjs/gruntjs.com#103]
That would be great if http://gruntjs.com/getting-started started with a very simple and straightforward tutorial showing how to get from zero, to a basic grunt task, like minifying a javascript file, in as few steps as possible, as few commands as possible, and with the smallest Gruntfile.js possible.

Right now there is a ton of info on that page and the "getting started" of it is pretty tough to sort out.

**Comment by allan-bonadio** [comment]
So I'm not the only one.  Here's some specific issues with it:

- what is it?  Your front page trumpets all this stuff that it does, "Automation".  Guess what, a programmable calculator can do automation.  A shell script can do automation.  What's special about Grunt?  Why do I have to learn the Grunt language if I already know how to do shell scripting or a real language like Python?  Does it do what Make or Rake or Maven or Ant does?  You need to answer that question.  (or maybe the front page should answer it.)

- Grunt Versions.  Until just now, it seemed like I had version 0.1.13 installed cuz that's what I get when I type in "grunt".  Turns out that's the grunt-cli version number, not the main version number.  Might be nice to clear that up or tell them to do a 'grunt --version'  - that sortof tells the whole story.

- How the CLI works: this is theory.  Talk about it after I (the audience) have something working.  Otherwise it doesn't make sense.  "Because of this, you can run grunt from any subfolder in your project."  whoop de do.  I can also run 'ls' from any subfolder in my project.  Or any subfolder on my entire machine.  Then, you talk about the 'Gruntfile', which you haven't defined yet.  

- Working with an existing Grunt project: I took a project, ansi-regex.  It's so tiny it's 105 bytes.  It's got a package.json file and I made an empty file named Gruntfile.js - you haven't told us the rules for a Gruntfile yet.  npm install worked fine, but grunt just got a bunch of error messages - not too surprising.  

This page isn't "Getting Started" - this is more of a "Guide to getting your project adapted for Grunt".  Written for someone who's already gone through a tutorial, and knows what Grunt can do that Bash can't.  

You need a tutorial.  You need to make a project that uses it - a SIMPLE project that a person can read all the sources in like 5 min or 30 min.  zip it or tarball it and the user downloads it.  Then you guide them by hand, show them a few Grunt commands that do fabulous things, why Grunt is special.  And you must guarantee that the reader is successful - first impressions do count.  My first impression is that it's buggy software that spews error messages, and it does the same thing as Bash, anyway.  And, you have to remember that your average reader is not well-versed in Grunt and is probably weak at Nodejs, too.  After all, if I knew Grunt, I wouldn't have to read your tutorial.

**Comment by distilledhype** [comment]
@allan-bonadio that's great feedback. Thanks!

**Comment by allan-bonadio** [comment]
thanks for being open minded about it; sometimes I can be a bit harsh about docs.  I checked out nvd3 yesterday; it is far worse, zero documentation, and the "simple" example took me 1/2 hour to get running.
